default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: guilds_dev
  host: localhost
  pool: 5
  username: guilds
  password: guilds

test:
  adapter: postgresql
  encoding: unicode
  database: guilds_test
  host: localhost
  pool: 5
  username: guilds
  password: guilds

staging:
  adapter: postgresql
  encoding: unicode
  database: guilds_staging
  host: localhost
  pool: 5
  username: guilds
  password: guilds

production:
  adapter: postgresql
  encoding: unicode
  database: guilds
  host: localhost
  pool: 5
  username: guilds
  password: guilds